---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: post
framework_version: 3.1.1
serverless_language: node
polling_url: ''
polling_headers: ''
polling_body: ''
id: 305419
custom_fields:
- keyname: refresh_token
  name: Refresh Token
  field_type: password
  required: true
  placeholder: AMf-vBw...
  instructions: 'Run the setup script to obtain this value. See plugin description for link. Update if you change your Tweek password.

    '
- keyname: calendar_name
  name: Calendar Name
  field_type: text
  required: false
  placeholder: My calendar
  instructions: Leave blank to use your default calendar.
- keyname: week_start_day
  name: Week Start Day
  field_type: select
  required: true
  default: Monday
  options:
  - Monday
  - Sunday
- keyname: time_format
  name: Time Format
  field_type: select
  required: true
  default: 12h
  options:
  - 12h
  - 24h
name: Tweek
refresh_interval: 30
